ifeq ($(strip $(SATURN_SAMPLE_COMMON)),)
$(error "Please set SATURN_SAMPLE_COMMON in your environment.  This should point to the root of the common directory." )
endif

export SAMPLE=01-Sprite

include $(SATURN_SAMPLE_COMMON)/Source/Makefile
